---
#
# Static website
#
apiVersion: v1
kind: Service
metadata:
  name: bot-timerboard
spec:
  ports:
  - port: 80
  selector:
    app: bot-timerboard
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bot-timerboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bot-timerboard
    spec:
      containers:
      - name: bot-timerboard-static
        image: andimiller/bot-timerboard
        ports:
        - containerPort: 80
          protocol: "TCP"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
---
#
# Routing
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bot-timerboard-tls 
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - bot.timerboard.net
    secretName: bot-timerboard-tls 
  rules:
  - host: bot.timerboard.net
    http:
      paths:
      - path: /
        backend:
          serviceName: bot-timerboard
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bot-timerboard
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: timerboard.net
    http:
      paths:
      - path: /
        backend:
          serviceName: timerboard-static
          servicePort: 80
